#!/bin/bash
set -e
# 1. pré-télécharge les poids (vite)
python -c "import torchvision; torchvision.models.resnet18(weights='IMAGENET1K_V1')"
# 2. lance Flask en ARRIÈRE-PLAN (ne bloque pas)
nohup python server.py --host=0.0.0.0 --port=5000 &